# Minimal yamllint config with no formatting rules enabled (prettier handles those)
rules:
  quoted-strings:
    required: only-when-needed
    extra-allowed: ["{|}"]
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: true
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
